import {readFile,writeFile,readdir} from 'node:fs/promises';
const root=new URL('../locales/',import.meta.url);
const catalog={};
for(const name of (await readdir(root)).filter(name=>name.endsWith('.json')).sort()) {
  const entries=JSON.parse(await readFile(new URL(name,root),'utf8'));
  for(const [key,value] of Object.entries(entries)) {
    if(key!==key.trim()||!key)throw new Error(`${name}: UI keys must be nonempty and trimmed`);
    if(!value||typeof value.en!=='string'||!value.en||typeof value.es!=='string'||!value.es)throw new Error(`${name}: incomplete translation for ${key}`);
    if(catalog[key]&&JSON.stringify(catalog[key])!==JSON.stringify(value))throw new Error(`${name}: conflicting translation for ${key}`);
    catalog[key]=value;
  }
}
const output='/* Generated by npm run locales; edit the JSON catalogs. */\n'+`globalThis.OrchestrixLocaleCatalog=Object.freeze(${JSON.stringify(catalog,null,2)});\n`;
const path=new URL('catalog.js',root);
if(process.argv.includes('--check')) {
  if(await readFile(path,'utf8')!==output)throw new Error('Stale locale catalog: run npm run locales');
} else await writeFile(path,output);
console.log(`${Object.keys(catalog).length} UI entries: English, Portuguese, Spanish.`);
