/* Diagnostics presents scoped observations; it never creates jobs or grants permissions. */
(() => {
  'use strict';
  const {html,t}=window.OrchestrixI18n;
  const checkLabels={config:'Configuração da conexão',identity:'Identidade da conexão',catalog:'Catálogo do provedor',access:'Acesso aos recursos',reasoning:'Raciocínio',context:'Contexto',functionCalling:'Chamadas de ferramentas',streaming:'Streaming',nativeWeb:'Busca web nativa',structuredOutput:'Saída estruturada',fastMode:'Modo rápido',nativeMultiAgent:'Agentes nativos do provedor',sandbox:'Sandbox de execução',approval:'Aprovações de execução',fullAccess:'Acesso completo à máquina',usage:'Cotas da conta',credits:'Créditos da API',providerSpecific:'Configuração específica do provedor',nativeDelegationPolicy:'Política de delegação nativa',orchestrixMultiAgent:'Orquestração do Orchestrix'};
  const featureLabels={...checkLabels,deployment:'Deployment',regionProfile:'Região e perfil',generationMethods:'Operações de geração',nativeDelegation:'Delegação nativa do provedor'};
  const phases={queued:'Diagnóstico na fila',running:'Verificando a conexão',completed:'Diagnóstico concluído',cancelled:'Diagnóstico cancelado',failed:'Diagnóstico interrompido'};
  const reportStatuses={complete:'As informações disponíveis foram verificadas.',partial:'Algumas capacidades ainda não foram verificadas.',blocked:'A conexão depende de autenticação ou de um adaptador oficial.',failed:'Não foi possível concluir todas as verificações.',cancelled:'O diagnóstico foi cancelado. Resultados tardios não serão aplicados.'};
  const checkStatus={passed:'Confirmado',failed:'Falhou',pending:'Pendente',blocked:'Bloqueado',skipped:'Não se aplica',unknown:'Não verificado'};
  const availability={available:'Disponível',unavailable:'Indisponível',unknown:'Não verificado','not-applicable':'Não se aplica'};
  const support={supported:'Suportado',unsupported:'Não suportado',unknown:'Suporte não informado','not-applicable':'Não se aplica'};
  const policies={disabled:'Desativado pela política',enabled:'Ativado pela política','requires-user-grant':'Requer permissão do usuário','orchestrator-managed':'Gerenciado pelo Orchestrix',inherited:'Política herdada',unknown:'Política não informada'};
  const sourceLabels={'provider-metadata':'Metadados do provedor','provider-documentation':'Documentação do provedor','runtime-observation':'Observação oficial do runtime','runtime-metadata':'Metadados do runtime',configuration:'Configuração da conexão',policy:'Política do Orchestrix','connection-state':'Estado da conexão','catalog-observation':'Consulta do catálogo'};
  const detailLabels={levels:'Níveis de raciocínio',modes:'Modos disponíveis',inputTokens:'Tokens de entrada',outputTokens:'Tokens de saída',windowTokens:'Janela de contexto',tokens:'Tokens',modalities:'Modalidades',methods:'Operações do modelo',modelCount:'Recursos informados',supportedCount:'Recursos com suporte',unsupportedCount:'Recursos sem suporte',unknownCount:'Recursos sem informação',remainingPercent:'Cota restante',usedPercent:'Cota utilizada',resetAt:'Renovação da cota',balance:'Saldo',currency:'Moeda',amount:'Créditos',region:'Região',deployment:'Deployment',profile:'Perfil AWS',project:'Projeto',scope:'Escopo',serviceTier:'Camada de serviço',fastTier:'Camada rápida',multiAgentVersion:'Versão de agentes nativos',agentsEnabled:'Agentes nativos configurados',sandbox:'Sandbox de execução',approvalPolicy:'Política de aprovação',observedState:'Estado observado',accessVerified:'Acesso verificado',authenticationRequired:'Autenticação necessária'};
  Object.assign(detailLabels,{resourceCount:'Recursos informados',serviceTiers:'Camadas de serviço',defaultServiceTier:'Camada padrão',version:'Versão de agentes nativos',versions:'Versões de agentes nativos',currentMode:'Sandbox configurado',currentPolicy:'Aprovação configurada',executionGrantVerified:'Permissão de execução confirmada',currentConfigurationAllowsFullAccess:'Configuração permite acesso completo',configured:'Configurado',managementCatalogSeparate:'Catálogo de administração separado',inferenceAccessVerified:'Acesso de inferência confirmado',regionConfigured:'Região configurada',authMethod:'Método de autenticação',profileCatalogObserved:'Perfis de inferência observados',executionAccessVerified:'Acesso de execução confirmado',antigravityRuntime:'Runtime Antigravity',runtimeState:'Estado observado no runtime',policyAppliedToRuntime:'Política aplicada ao runtime',runtimeSettingChanged:'Configuração do runtime alterada',nativeDelegationRequired:'Delegação nativa necessária'});
  Object.assign(detailLabels,{availablePercent:'Cota disponível',remaining:'Créditos restantes',spent:'Créditos utilizados'});
  const codeMessages={'authentication-required':'Confirme a autenticação no provedor antes de consultar os recursos.','access-denied':'Esta credencial não tem permissão para listar recursos.','rate-limited':'O provedor limitou a consulta de catálogo. Aguarde e tente novamente.',timeout:'A consulta demorou mais que o esperado. Tente novamente.','host-unavailable':'O serviço de descoberta não está disponível nesta sessão.','adapter-unavailable':'Não há um adaptador oficial disponível para verificar esta conexão.','credentials-missing':'A credencial desta sessão não está disponível.','runtime-identity-required':'A identidade e a autenticação do runtime ainda não foram confirmadas.','inference-identity-not-verified':'A consulta de catálogo não verifica a identidade de inferência.','execution-access-not-verified':'O acesso de execução ainda não foi verificado.','partial-catalog-observed':'A consulta retornou um catálogo parcial.','catalog-scope-unbound':'A consulta não corresponde ao escopo desta conexão.','invalid-catalog':'O catálogo recebido não pôde ser validado.','invalid-configuration':'Revise a configuração desta conexão.','catalog-adapter-required':'O provedor ainda não disponibilizou uma consulta de catálogo compatível.','catalog-pending':'A consulta de recursos está em andamento.',cancelled:'O diagnóstico foi cancelado. Resultados tardios não serão aplicados.',failed:'Não foi possível concluir a consulta de recursos.','scope-mismatch':'A observação pertence a outro escopo de conexão.','revision-mismatch':'A observação pertence a uma revisão anterior da conexão.','not-reported':'A fonte não informou este recurso.','observed-unsupported':'A fonte confirmou que este recurso não é suportado.'};
  const explanations={
    config:'A configuração é verificada sem executar uma tarefa.',identity:'As observações precisam pertencer a esta conexão e à revisão atual.',catalog:'Somente os recursos informados nesta consulta fazem parte deste diagnóstico.',access:'A listagem de modelos não confirma permissão para executar tarefas.',reasoning:'Os níveis disponíveis dependem do modelo e do runtime.',context:'O tamanho de contexto só é mostrado quando informado pela fonte.',functionCalling:'Suporte a ferramentas não concede acesso aos arquivos da máquina.',fastMode:'A camada rápida é independente do nível de raciocínio.',nativeMultiAgent:'Suporte do modelo, configuração do runtime e política de delegação são verificados separadamente.',sandbox:'O sandbox limita as operações executadas pelo runtime.',approval:'A política de aprovação é uma configuração de execução do usuário.',fullAccess:'Acesso completo exige uma permissão de execução explícita; uma API de nuvem não concede acesso à máquina.',usage:'Cotas desconhecidas permanecem sem estimativa.',credits:'Créditos só são mostrados quando fornecidos por uma fonte observável.',nativeDelegationPolicy:'A delegação nativa fica desativada por padrão quando o Orchestrix coordena o trabalho.',orchestrixMultiAgent:'A orquestração do Orchestrix é independente dos agentes nativos de um provedor.'
  };
  const groups=[['Capacidades dos modelos',['reasoning','context','functionCalling','streaming','nativeWeb','structuredOutput']],['Velocidade e colaboração',['fastMode','nativeMultiAgent','nativeDelegation','orchestrixMultiAgent']],['Permissões de execução',['sandbox','approval','fullAccess']],['Uso e configuração do provedor',['usage','credits','deployment','regionProfile','generationMethods']]];
  const scopeLabels={connectionId:'Conexão',provider:'Provedor',endpoint:'Endpoint',authMethod:'Método de autenticação',deployment:'Deployment',region:'Região',project:'Projeto',runtime:'Runtime',runtimeVersion:'Versão do runtime',revision:'Revisão'};
  const icon=(name)=>`<svg viewBox="0 0 24 24" aria-hidden="true">${name==='check'?'<path d="m5 12 4 4L19 6"/>':name==='cross'?'<path d="m6 6 12 12M18 6 6 18"/>':name==='clock'?'<circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/>':name==='shield'?'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>':'<circle cx="12" cy="12" r="8"/><path d="M12 10v6M12 7v.1"/>'}</svg>`;
  const list=value=>Array.isArray(value)?value:[];
  const bounded=value=>String(value??'').slice(0,400);
  const value=(item,h)=>h.esc(bounded(item));
  const locale=()=>window.OrchestrixI18n.language;
  const number=item=>new Intl.NumberFormat(locale()).format(item);
  function timestamp(date) {const parsed=new Date(date||'');return Number.isFinite(parsed.getTime())?new Intl.DateTimeFormat(locale(),{dateStyle:'medium',timeStyle:'short'}).format(parsed):t('Não informado');}
  function reportOf(c) {return c?.diagnostics&&typeof c.diagnostics==='object'?c.diagnostics:null;}
  function featuresOf(report) {const features=report?.features;return Array.isArray(features)?Object.fromEntries(features.filter(x=>x?.id).map(x=>[x.id,x])):features&&typeof features==='object'?features:{};}
  function countData(report) {
    const checks=list(report?.checks),models=list(report?.models);
    const summary=report?.summary||{};
    const finite=(raw,fallback)=>Number.isFinite(raw)&&raw>=0?raw:fallback;
    return {checks:checks.length,total:finite(summary.totalChecks,checks.length),finished:checks.filter(x=>x.status!=='pending').length,
      available:finite(summary.resources?.available,models.filter(x=>x.available==='available').length),unavailable:finite(summary.resources?.unavailable,models.filter(x=>x.available==='unavailable').length),unknown:finite(summary.resources?.unknown,models.filter(x=>x.available==='unknown').length)};
  }
  function statusBadge(status,label) {return html`<span class="diagnostic-badge diagnostic-${status}">${icon(['passed','available','supported'].includes(status)?'check':['failed','unavailable','unsupported'].includes(status)?'cross':status==='pending'?'clock':'info')}${t(label)}</span>`;}
  function counts(report) {const c=countData(report);return html`<p class="diagnostic-count-label">Disponibilidade dos recursos</p><dl class="diagnostic-counts"><div data-diagnostic-count="available"><dt>Disponíveis</dt><dd>${number(c.available)}</dd></div><div data-diagnostic-count="unavailable"><dt>Indisponíveis</dt><dd>${number(c.unavailable)}</dd></div><div data-diagnostic-count="unknown"><dt>Não verificados</dt><dd>${number(c.unknown)}</dd></div></dl>`;}
  function progress(report,h) {const c=countData(report),running=['queued','running'].includes(report?.phase);return html`<div class="diagnostic-progress" role="status" aria-live="polite" aria-atomic="true"><span>${t(phases[report?.phase]||'Diagnóstico ainda não realizado')}</span>${running?html`<span>${number(c.finished)} / ${number(c.total)} ${t('verificações concluídas')}</span><progress aria-label="Progresso do diagnóstico" ${c.total?`value="${c.finished}" max="${c.total}"`:''}></progress>`:''}</div>`;}
  function reportStatus(report) {return reportStatuses[report?.status]?html`<p class="diagnostic-status-note diagnostic-status-${report.status}">${t(reportStatuses[report.status])}</p>`:'';}
  function actions(c,report,h,button,compact=false) {const running=['queued','running'].includes(report?.phase);return html`<div class="diagnostic-actions">${compact?button(t('Ver diagnóstico'),'diagnostics',c.id,h,true):''}${running?button(t('Cancelar diagnóstico'),'cancel-diagnostics',c.id,h):button(t('Verificar novamente'),'recheck-diagnostics',c.id,h)}${!compact?button(t('Ver conexão'),'inspect',c.id,h):''}</div>`;}
  function card(c,h,button) {const report=reportOf(c);if(!report)return '';return html`<section class="diagnostic-card" data-diagnostic-connection="${value(c.id,h)}"><header><span class="diagnostic-emblem">${icon('shield')}</span><div><h3>Diagnóstico da conexão</h3><p>${value(c.name,h)}</p></div></header>${progress(report,h)}${reportStatus(report)}${counts(report)}${actions(c,report,h,button,true)}</section>`;}
  function detailsOf(details,h,depth=0) {
    if(!details||typeof details!=='object')return '';
    const items=Object.entries(detailLabels).filter(([key])=>details[key]!==undefined&&details[key]!==null).map(([key,label])=>{
      const raw=details[key];let shown;
      if(typeof raw==='boolean')shown=t(raw?'Sim':'Não');
      else if(typeof raw==='number'&&Number.isFinite(raw))shown=number(raw)+(['remainingPercent','usedPercent','availablePercent'].includes(key)?'%':'');
      else if(Array.isArray(raw))shown=raw.filter(x=>['string','number'].includes(typeof x)).slice(0,20).map(bounded).join(', ');
      else if(typeof raw==='string')shown=key==='resetAt'?timestamp(raw):bounded(raw);
      else return '';
      return html`<div><dt>${t(label)}</dt><dd>${value(shown,h)}</dd></div>`;
    }).filter(Boolean);
    const credits=depth===0&&details.credit&&typeof details.credit==='object'?detailsOf(details.credit,h,1):'';
    return html`${items.length?html`<dl class="diagnostic-facts">${items.join('')}</dl>`:''}${credits?html`<div class="diagnostic-credit-details"><strong>Créditos informados pela fonte</strong>${credits}</div>`:''}`;
  }
  function provenance(entries,h) {
    const sources=list(entries).slice(0,8).map(source=>{
      if(typeof source==='string')return html`<span>${value(source,h)}</span>`;
      if(!source||typeof source!=='object')return '';
      const kind=source.kind||source.type;
      const fields=[kind?t(sourceLabels[kind]||'Fonte de observação'):null,source.operation,source.field,source.observedAt?timestamp(source.observedAt):null].filter(x=>typeof x==='string'&&x);
      return fields.length?html`<span>${value(fields.join(' · '),h)}</span>`:'';
    }).filter(Boolean);
    return sources.length?html`<div class="diagnostic-provenance"><strong>Origem da informação</strong>${sources.join('')}</div>`:'';
  }
  function featureView(id,feature,h) {
    const f=feature||{support:'unknown',available:'unknown',observed:false},state=Object.hasOwn(availability,f.available)?f.available:'unknown';
    const supported=Object.hasOwn(support,f.support)?f.support:'unknown';
    return html`<article class="diagnostic-feature" data-diagnostic-feature="${id}"><header><h5>${t(featureLabels[id]||'Recurso')}</h5>${statusBadge(state,availability[state])}</header><div class="diagnostic-feature-meta"><span>${t(support[supported])}</span>${f.effectivePolicy?html`<span>${t(policies[f.effectivePolicy]||policies.unknown)}</span>`:''}<span>${t(f.observed?'Observado nesta conexão':'Sem observação confirmada')}</span></div>${explanations[id]?html`<p class="diagnostic-hint">${t(explanations[id])}</p>`:''}${detailsOf(f.details,h)}${provenance(f.provenance,h)}</article>`;
  }
  function scopeView(report,h) {const scope=report?.scope||{};return html`<details class="diagnostic-scope"><summary>Escopo e fontes do diagnóstico</summary><dl class="diagnostic-facts">${Object.entries(scopeLabels).filter(([key])=>['string','number'].includes(typeof scope[key])).map(([key,label])=>html`<div><dt>${t(label)}</dt><dd>${value(scope[key],h)}</dd></div>`).join('')}<div><dt>Iniciado em</dt><dd>${value(timestamp(report?.startedAt),h)}</dd></div><div><dt>Concluído em</dt><dd>${value(timestamp(report?.completedAt),h)}</dd></div></dl><p class="diagnostic-hint">Este resultado pertence à conexão e à revisão indicadas. Uma alteração requer uma nova verificação.</p></details>`;}
  function checklist(report,h) {return html`<details class="diagnostic-checklist" ${['queued','running'].includes(report?.phase)?'open':''}><summary>Verificações da conexão</summary><ol>${list(report?.checks).map(check=>{const status=Object.hasOwn(checkStatus,check.status)?check.status:'unknown';return html`<li data-diagnostic-check="${value(check.id,h)}" data-check-status="${status}"><div><strong>${t(checkLabels[check.id]||'Verificação do provedor')}</strong>${statusBadge(status,checkStatus[status])}</div>${codeMessages[check.code]?html`<p class="diagnostic-hint diagnostic-check-message">${t(codeMessages[check.code])}</p>`:explanations[check.id]?html`<p class="diagnostic-hint">${t(explanations[check.id])}</p>`:''}${detailsOf(check.details,h)}${provenance(check.provenance,h)}</li>`;}).join('')}</ol></details>`;}
  function policyView(report,h) {const policy=report?.policy||{},native=policy.nativeDelegation||{},state={enabled:'Ativado no runtime',disabled:'Desativado no runtime',unknown:'Estado do runtime não informado'};return html`<section class="diagnostic-policy"><h4>Quem coordena o trabalho</h4><p class="diagnostic-hint">O nível de raciocínio, a camada rápida e os agentes nativos são capacidades independentes. O nome de um modo não confirma sua ativação no runtime.</p><dl class="diagnostic-facts"><div><dt>Delegação nativa do provedor</dt><dd>${t(policies[native.effective]||policies.unknown)}</dd></div><div><dt>Estado observado no runtime</dt><dd>${t(state[native.observedRuntimeState]||state.unknown)}</dd></div><div><dt>Orquestração do Orchestrix</dt><dd>${t(policy.orchestrixMultiAgent?.status==='planned'?'Planejada no Orchestrix':'Gerenciada pelo Orchestrix')}</dd></div><div><dt>Permissões da máquina</dt><dd>${t(policies[policy.hostPermissions?.effective]||'Requer permissão do usuário')}</dd></div></dl><p class="diagnostic-hint">A política de delegação do Orchestrix não altera a configuração do provedor neste diagnóstico.</p></section>`;}
  function modelsView(report,h) {return html`<section class="diagnostic-models"><h4>Recursos observados</h4>${list(report?.models).length?list(report.models).map(model=>html`<details class="diagnostic-model" data-diagnostic-model="${value(model.id,h)}"><summary><span><strong>${value(model.name||model.id,h)}</strong><small>${value(model.id,h)}${model.kind?` · ${value(model.kind,h)}`:''}</small></span>${statusBadge(Object.hasOwn(availability,model.available)?model.available:'unknown',availability[model.available]||availability.unknown)}</summary><div class="diagnostic-model-details"><p class="diagnostic-hint">O acesso de execução é verificado separadamente do catálogo.</p>${provenance(model.access?.provenance,h)}<div class="diagnostic-feature-grid">${Object.entries(model.features||{}).filter(([id])=>Object.hasOwn(featureLabels,id)).map(([id,f])=>featureView(id,f,h)).join('')}</div></div></details>`).join(''):html`<p class="diagnostic-empty">Nenhum recurso observado nesta conexão.</p>`}</section>`;}
  function view(c,h,button) {const report=reportOf(c);return html`<section id="connection-diagnostics" class="connection-diagnostics conn-inspector" data-diagnostic-connection="${value(c.id,h)}"><header class="diagnostic-heading"><span class="diagnostic-emblem">${icon('shield')}</span><div><h3>Diagnóstico da conexão</h3><p>${value(c.name,h)}</p></div></header>${progress(report,h)}${reportStatus(report)}${report?counts(report):''}<p class="diagnostic-intro">Veja o que está disponível, o que depende de permissão e o que o provedor ainda não informou.</p>${actions(c,report,h,button)}${!report?html`<p class="diagnostic-empty">Inicie uma verificação para consultar os recursos desta conexão.</p>`:html`${scopeView(report,h)}${checklist(report,h)}${groups.map(([label,ids])=>html`<section class="diagnostic-group"><h4>${t(label)}</h4><div class="diagnostic-feature-grid">${ids.map(id=>featureView(id,featuresOf(report)[id],h)).join('')}</div></section>`).join('')}${policyView(report,h)}${modelsView(report,h)}`}</section>`;}
  window.OrchestrixDiagnosticsView=Object.freeze({view,render:view,card});
})();
