/* Progressive session entry and project organization. */
(() => {
  'use strict';
  const {html,t}=window.OrchestrixI18n;
  function entryView(state,h) {
    return h.pageHead(t('PROJETOS'),t('Um lugar para suas sessões'),t('Organize sessões que compartilham um objetivo e um contexto.'),h.action(t('Voltar à conversa'),'chat'))+html`<section class="entry-card settings-card"><h2>Criar projeto</h2><form id="entry-form"><label class="form-label" for="entry-name">Nome do projeto</label><input id="entry-name" name="project" required maxlength="50" autocomplete="off" placeholder="Nome do projeto"><label class="form-label" for="entry-path">Diretório de trabalho</label><input id="entry-path" name="path" maxlength="180" autocomplete="off" placeholder="Caminho da pasta"><p class="field-hint">Você pode definir o diretório agora ou depois.</p><label class="form-label" for="entry-context">Contexto compartilhado</label><textarea id="entry-context" name="context" rows="3" maxlength="4000" placeholder="Objetivo, referências e instruções para as sessões deste projeto"></textarea><div class="form-actions"><button class="button primary" type="submit">Criar projeto e sessão</button></div></form></section>`;
  }
  function chatView(state,h) {
    const chat=state.chat;
    const active=state.tasks.find(task=>task.id===chat.activeTaskId);
    const welcome=!chat.messages.some(message=>message.role==='user')&&!chat.exampleVisible;
    const cards=welcome?[]:chat.taskIds.map(id=>state.tasks.find(task=>task.id===id)).filter(Boolean).reverse();
    const header=welcome?html`<header class="welcome-stage"><span class="identity-symbol welcome-symbol" aria-hidden="true"><img class="identity-light" src="assets/brand/transparent/symbol-graphite.png" alt=""><img class="identity-dark" src="assets/brand/transparent/symbol-indigo.png" alt=""></span><h1>O que vamos criar hoje?</h1></header>`:h.pageHead(state.isLoose?t('SESSÃO'):t('SESSÃO DO PROJETO'),chat.name,state.isLoose?t('Sua conversa e seu próximo passo.'):state.project,h.action(t('Novo trabalho nesta conversa'),'chat-new'));
    const messages=welcome?'':chat.messages.map(message=>html`<article class="chat-message ${message.role==='user'?'from-user':'from-orchestrator'}" aria-label="${message.role==='user'?t('Você'):'Orchestrix'}"><div class="chat-speaker">${message.role==='user'?t('Você'):html`${h.icon('layers')}Orchestrix`}</div><p>${h.esc(message.text)}</p>${message.plan?html`<ol class="chat-plan">${message.plan.map(step=>html`<li>${h.esc(step)}</li>`).join('')}</ol>`:''}</article>`).join('');
    const suggestions=welcome?html`<div class="prompt-suggestions" aria-label="Ideias para começar">${[
      [t('Corrigir um problema'),t('Quero corrigir um problema no meu projeto. Ajude-me a entender a causa e propor uma solução.')],
      [t('Criar uma funcionalidade'),t('Quero criar uma funcionalidade no meu projeto. Vamos definir o comportamento e os critérios para revisar o resultado.')],
      [t('Entender meu código'),t('Ajude-me a entender a estrutura do meu projeto e identificar os próximos passos.')]
    ].map(([label,prompt])=>html`<button type="button" data-prompt="${h.esc(prompt)}">${h.icon(label===t('Corrigir um problema')?'code':label===t('Criar uma funcionalidade')?'plus':'book')}${label}</button>`).join('')}</div>`:'';
    const setup=welcome?html`<section class="quick-start" aria-label="Comece do seu jeito"><div class="quick-start-grid"><button class="quick-start-card" data-action="connect-account">${h.icon('plug')}<strong>Conectar conta</strong><span>Traga os agentes que você já usa.</span><b aria-hidden="true">↗</b></button><button class="quick-start-card" data-action="onboarding">${h.icon('folder')}<strong>Abrir ou criar projeto</strong><span>Reúna sessões e contexto.</span><b aria-hidden="true">↗</b></button><a class="quick-start-card" href="help.html" target="_blank" rel="noopener">${h.icon('book')}<strong>Ajuda e tutoriais</strong><span>Encontre seu próximo passo.</span><b aria-hidden="true">↗</b></a></div></section>`:'';
    const target=active?html`<p class="chat-target">Conversando sobre: <strong>${h.esc(active.title)}</strong>.</p>`:'';
    const destination=state.isLoose?html`<button type="button" class="context-action" data-action="session-directory">${h.icon('folder')}${h.esc(state.projectPath||t('Definir diretório'))}</button><button type="button" class="context-action" data-action="session-attach">${h.icon('layers')}Associar a projeto</button>`:html`<button type="button" class="context-action" data-action="project-context">${h.icon('folder')}${h.esc(state.project)}</button>`;
    return html`<div class="conversation-surface ${welcome?'is-welcome':'has-conversation'}">${header}<div class="chat-layout ${cards.length?'has-work':'no-work'}"><section class="chat-main" aria-label="Mensagem e conversa">${welcome?setup+suggestions:''}<div class="chat-transcript" role="log" aria-label="Conversa" aria-live="polite" aria-relevant="additions text">${messages}</div><form id="chat-form" class="chat-composer"><label class="sr-only" for="chat-message">Mensagem</label>${target}<textarea id="chat-message" name="message" rows="2" required maxlength="2000" placeholder="Descreva o que você quer desenvolver…" aria-describedby="chat-composer-hint">${h.esc(chat.draft)}</textarea><div class="composer-context"><div class="session-destination">${destination}</div><span class="automatic-mode">${h.icon('checkCircle')}Orquestração automática</span></div><div class="chat-composer-footer"><p id="chat-composer-hint">Enter para enviar · Shift + Enter para nova linha.</p><button type="submit" class="button primary">${h.icon('arrow')}Enviar</button></div></form></section>${cards.length?html`<aside class="chat-work" aria-label="Trabalhos da sessão"><div class="chat-work-heading"><h2>Seu trabalho</h2><p>Um próximo passo de cada vez.</p></div>${cards.map(task=>window.OrchestrixWorkspace.chatTaskCard(task,state,h)).join('')}</aside>`:''}</div></div>`;
  }
  function syncLayout() { /* Entry order is shared by desktop and compact layouts. */ }
  window.OrchestrixExperience=Object.freeze({chatView,entryView,syncLayout});
})();
